#!/usr/bin/env ruby
# frozen_string_literal: true

# for dev purposes
require "bundler/setup" if ENV["CENTRA_GEM_DEV"]

require "centra"
require "centra/cli"
require "centra/db"

args = Centra::ImportCLI.parse!(name: "centra_product_import")

Centra.configure do |config|
  config.logger = args.fetch(:logger, Centra::NullLogger.new)
  config.database.table_names.merge!(args.fetch(:table_names, {}))
end

print "Reading Centra product export file.."
file = File.read(args[:centra_export_file])
puts "done!"
print "Parsing#{' and anonymizing ' if args[:anonymize]} CSV-file (this may take a while).."
centra_csv = Centra::ProductCSV.new(file, anonymize: args[:anonymize])
puts "done!"
product_filter = Centra::ProductFilter.new(
  date_range: Centra::DateRange.new(args[:start_date], args[:end_date]),
  countries: args.fetch(:countries, [])
)
products = Centra::Products.new(centra_csv, product_filter)

print "Connecting to database.."
connection = Centra::DB::Connection.new(args[:db])
puts "done!"

if args[:reset_tables]
  print "Dropping and creating products table.."
  migration = Centra::Migrations::CreateProducts.new(connection)
  migration.down
  migration.up
  puts "done!"
end

print "Importing products to database, this may take a while.."
Centra::DB::ProductImport.call(products, connection: connection)
puts "done!"
